## Server
server:
  port: 3000

## Logging
logging:
  level:
    root: info
    org.hibernate.SQL: trace
    demo: trace

spring:
  datasource:
    #url: jdbc:h2:mem:testdb
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100